# Generated by Django 4.0.5 on 2022-11-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='does',
            field=models.BooleanField(default=False),
        ),
    ]
