# Generated by Django 4.0.5 on 2022-11-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_does'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='does',
            new_name='do_success',
        ),
    ]
